name = "PProf"
uuid = "e4faabce-9ead-11e9-39d9-4379958e3056"
authors = ["Valentin Churavy <v.churavy@gmail.com>", "Nathan Daly <nhdaly@gmail.com>"]
version = "1.1.1"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
pprof_jll = "cf2c5f97-e748-59fa-a03f-dda3c62118cb"

[compat]
OrderedCollections = "1.1"
ProtoBuf = "0.7, 0.8"
julia = "1.3"
pprof_jll = "0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
